config/routes.rb
Rails.application.routes.draw do

 
  devise_for :users

  root 'welcome#index'
  get 'welcome/index'
  resources :pictures, except: ["index"]
  resources :galleries, except: ["index"]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gallery.rb
class Gallery < ApplicationRecord
    has_many :pictures, dependent: :destroy

    # has_attached_file :image, styles: { large: "800x800>", thumb: "100x100>" }  #, default_url: "/images/:style/missing.png"
    # validates_attachment :image, 
    # content_type: { content_type: ["image/jpeg", "image/jpg", "image/png"] },
    # size: { in: 0..6000.kilobytes }
    
    has_attached_file :image, 
                    :styles => { large: "1080x650#", medium: "540x325#" }
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/JPG", "image/JPEG", "image/png", "image/PNG"]
    validates_attachment_file_name :image, :matches => [/png\Z/, /PNG\Z/, /jpe?g\Z/, /JPE?G\Z/  ]
    validates_attachment :image, size: { less_than: 5.megabytes }
    
    



end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :gallery
 
  has_attached_file :image, styles: { large: "1080x650", medium: "600x400", thumb: "100x100#" }  
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/JPG", "image/JPEG", "image/png", "image/PNG"]
  validates_attachment_file_name :image, :matches => [/png\Z/, /PNG\Z/, /jpe?g\Z/, /JPE?G\Z/ ]
  validates_attachment :image, size: { less_than: 5.megabytes }
  validates :image, :attachment_presence => true




end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end


#:registerable,

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  #before_action :authenticate_user! #from devise
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]

  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.order("created_at asc")
    
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
    @pictures = @gallery.pictures.order("sort_order asc")
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
  end

  # GET /galleries/1/edit
  def edit
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to root_path(:anchor => 'portfolio'), notice: 'Gallery was successfully created.' }
        format.json { render :show, status: :created, location: @gallery }
      else
        format.html { render :new }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to root_path(:anchor => 'portfolio'), notice: 'Gallery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:name, :description, :image, :sort_order)
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  #before_action :authenticate_user! #from devise
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to gallery_path(@picture.gallery_id), notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to gallery_path(@picture.gallery_id), notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @gallery_id = @picture.gallery_id
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to gallery_path(@gallery_id), notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:gallery_id, :name, :description, :sort_order, :image)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @galleries = Gallery.order("sort_order ASC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/galleries/_form.html.erb
<%#= form_with(model: gallery, local: true) do |form| %>
<%#= form_for @gallery, url: galleries_path do |form| %>
<%=form_for @gallery, html: { multipart: true } do |form| %>

  <% if gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% gallery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= form.label :image, "Gallery cover image (*Optional, can be added later)" %><br>
    <%= form.file_field :image %>
  </div>
   
  <hr>

  <div class="form-group col-md-6">
    <%= form.label :name, "Name (*required)" %>
    <%= form.text_field :name, id: :gallery_name, required: true, class: "form-control" %>
  </div>

  <div class="form-group col-md-6">
    <%= form.label :description %>
    <%= form.text_area :description, id: :gallery_description, class: "form-control" %>
  </div>
  
   <div class="form-group">
    <%= form.label :sort_order, "Sorting Order (optional)"  %>
    <%= form.number_field :sort_order, id: :gallery_order, class: "form-control col-xs-12 col-md-4"  %>
  </div>

  <div class="actions">
    <%= form.submit "Save", class:"btn btn-lg btn-success" %>
  </div>
  
<% end %>

app/views/galleries/edit.html.erb
<div class="container">
    <div class="row-fluid">
        <div class="col-xs-12">

<h1>Editing Gallery</h1>

<%= render 'form', gallery: @gallery %>

<%= link_to 'View gallery', @gallery %> |
<%= link_to 'Delete this gallery', @gallery, method: :delete, data: { confirm: 'Are you sure? This will delete any pictures in the gallery as well.' } %> |
<%= link_to 'Go back to portfolio', root_path(anchor: 'porfolio') %>


</div>
</div>

</div>

app/views/galleries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Galleries</h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Images</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @galleries.each do |gallery| %>
      <tr>
        <td><%= gallery.name %></td>
        <td><%= gallery.description %></td>
        <td> ### </td>
        <td><%= link_to 'Show', gallery %></td>
        <td><%= link_to 'Edit', edit_gallery_path(gallery) %></td>
        <td><%= link_to 'Destroy', gallery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gallery', new_gallery_path %>

app/views/galleries/new.html.erb
<div class="container">
    <div class="row-fluid">
        <div class="col-xs-12">

<h1>New Gallery</h1>

<%= render 'form', gallery: @gallery %>

<br>
<%= link_to 'Back to portfolio', root_path(:anchor => "portfolio") %>


</div>
</div>
</div>

app/views/galleries/show.html.erb
<section class="portfolio-show" %>
  <div class="container-fluid">
    <br>
    <h1>
   
      <span class= "float-sm-left" style="margin-left:20px;font-size:50%;">
        <%= link_to '<i class="fas fa-angle-double-left text-muted"></i> Back to Portfolios' .html_safe, root_path(:anchor => 'portfolio'), class:"text-muted" %>
      </span>
      <!-- <span class= "text-muted float-sm-left" style="margin-left:20px;font-size:50%;">-->
      <!--   <%#= link_to 'Our Portfolio', root_path(:anchor => 'portfolio'), class:"text-muted", style:"text-decoration: underline;" %> -->
      <!--  <i class="fas fa-angle-right text-muted"></i>-->
      <!--  <%#= @gallery.name %>-->
      <!--</span>-->
      <%= @gallery.name %>
      <% if user_signed_in? %>
        <small><small> 
          <%= link_to '<i class="fa fa-pencil-alt"></i>' .html_safe, edit_gallery_path(@gallery), class: "btn btn-sm btn-secondary" %>
          <%= link_to '<i class="fa fa-plus"></i> Add new picture' .html_safe,  new_picture_path(:gallery_id => @gallery.id), class: "btn btn-sm btn-success" %>
           <small class="text-muted"> &nbsp;(Admin only) </small>
        </small></small>
      <% end %>
    </h1>
    <p>
      <%= @gallery.description if @gallery.description.present? %>
    </p>
   <br>
    <div class = "row">
      <% if @gallery.pictures.present? %>
        <% @pictures.each do |picture| %>
          <div class="col-xs-12 col-md-6 col-lg-4" style="padding: 1rem;">
            <%= link_to picture_path(picture) do %>
              <%#= image_tag picture.image.url(:medium), alt: picture.try(:name), class:"img-fluid img-thumbnail" %>
              <% if picture.image.exists?(:medium) %>
                 <%= image_tag picture.image.url(:medium), alt: picture.try(:name), class:"img-fluid img-thumbnail" %>
              <% else %>
                 <%= image_tag picture.image.url(:large), alt: picture.try(:name), class:"img-fluid img-thumbnail" %>
              <% end %>
             
            <% end %>
              <p>
               <%= picture.try(:name) %>
                <% if user_signed_in? %>
                  <br><br>
                  <small class="text-muted"> (Admin only): </small>
                  <%= link_to '<i class="fa fa-pencil-alt"></i>' .html_safe, edit_picture_path(picture), class: "btn btn-sm btn-secondary" %>
                  <%= link_to '<i class="fa fa-times"></i>' .html_safe, picture, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
                  <br>
                  <small class="text-muted"><em>Display Order: </em><%= picture.sort_order || "none" %> </small>
                <% end %>
              </p>  
          </div>
        <% end %>
      <% else %>
        <p> There are currently no pictures in this gallery</p>
      <% end %>
    </div>
    
  </div>
</section>

<%= render 'welcome/contact_us_section' %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #111;">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to image_tag("kz-logo.jpg"), root_path, class: "navbar-brand-image", alt: "logo" %>  
  <%= link_to "Kathryn L. Zanoni Interior Design", root_path, class: "navbar-brand" %>
  
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <ul class="navbar-nav ml-auto">
      <li class="<%= 'active' if current_page?(root_path) %>">
        <%= link_to('Home', root_path, class:"nav-item nav-link") %>
      </li>
      <li><%= link_to('About', root_path(:anchor => 'about'), class:"nav-item nav-link") %></li>
      <li> <%= link_to('Services', root_path(:anchor => 'services'), class:"nav-item nav-link") %></li>
      <li><%= link_to('Portfolio', root_path(:anchor => 'portfolio'), class:"nav-item nav-link") %></li>
      <li><%= link_to('Contact', root_path(:anchor => 'contact'), class:"nav-item nav-link") %></li>
      <% if user_signed_in? %>
      <li><%= link_to('Sign out as admin',  destroy_user_session_path, :method => :delete, class:"nav-item nav-link btn btn-sm btn-danger") %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Kathryn L. Zanoni | Chicago Interior Design</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <div class="main">
    <%= render 'layouts/header' %>
    

        <% flash.each do |name, msg| %>
            <%= content_tag(:div, msg, class: "alert alert-info") %>
        <% end %>
        <!--breadcrumbs here?-->
        
          <%= yield %>
        
       
    </div>   
    <section class="footer text-muted text-center">
      <br><br>
      <p>
        <small>
          &copy 2018 <%= link_to 'Kathryn Zanoni Interior Design', new_user_session_path, class: "text-muted" %>
        </small>
      </p>
    </section>
  </body>
</html>

app/views/pictures/_form.html.erb
<%#= form_with(model: picture, local: true) do |form| %>
<%#= form_for picture, html: { multipart: true } do |form| %>
<%= form_for @picture, html: { multipart: true } do |form| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  
  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  
  <hr>

  <!--if params gallery present then dont show this-->
  <% if params[:gallery_id] %>
    <%= form.hidden_field :gallery_id, value: params[:gallery_id] %>
  <% else %>  
  <div class="form-group ">
    <%= form.label :gallery_id, "Gallery (*required)"  %>
    <%= form.collection_select :gallery_id, Gallery.order(:name),:id,:name, {include_blank: true, required: true, class: "form-control"}  %>
  </div>
  <% end %>
  

  <div class="form-group ">
    <%= form.label :name, "Caption (optional)" %>
    <%= form.text_field :name, id: :picture_name, class: "form-control col-xs-12 col-md-4"  %>
  </div>

  <div class="form-group">
    <%= form.label :description, "Description (optional)"  %>
    <%= form.text_area :description, id: :picture_description, class: "form-control col-xs-12 col-md-4"  %>
  </div>
  
  <div class="form-group">
    <%= form.label :sort_order, "Sorting Order (optional)"  %>
    <%= form.number_field :sort_order, id: :picture_order, class: "form-control col-xs-12 col-md-4"  %>
  </div>

  <div class="actions">
    <%= form.submit "Save", class:"btn btn-lg btn-success" %>
  </div>
  
<% end %>

app/views/pictures/edit.html.erb
<div class="container">
    <div class="row-fluid">
        <div class="col-xs-12">
            <h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'View', @picture %> |
<%= link_to 'Delete this picture', @picture, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Go back to gallery', gallery_path(@picture.gallery_id) if @picture.gallery_id.present? %>
            
        </div>
    </div>


</div>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pictures</h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Gallery</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.gallery %></td>
        <td><%= picture.name %></td>
        <td><%= picture.description %></td>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<div class="container">
    <div class="row-fluid">
        <div class="col-xs-12">

<br>
<h1>Add a new picture to your gallery</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Back', pictures_path %>


</div>
</div>
</div>

app/views/pictures/show.html.erb
<section class="portfolio-section">
  <div class="container">
  <div class="row-fluid">
    <div class="col-xs-12">

      <p id="notice"><%= notice %></p>
      
      
      <h2><span class= "text-muted float-sm-left" style=margin-left:20px;><%= link_to '<i class="fas fa-angle-double-left"></i>' .html_safe, gallery_path(@picture.gallery_id) %></span></h2>
      <br>  
        <p>
          <%= image_tag @picture.image.url(:large), class:"img-fluid img-thumbnail" %>
        </p>
         <p>
        <strong>Gallery:</strong>
        <%= link_to @picture.gallery.try(:name), gallery_path(@picture.gallery_id) %>
      </p>
        <% if @picture.name.present? %>
          <p>
            <strong>Image:</strong>
            <%= @picture.name %>
          </p>
        <% end %>
        <% if @picture.description.present? %>
        <p>
          <strong>Description:</strong>
          <%= @picture.description %>
        </p>
        <% end %>
   
        
        <% if user_signed_in? %>
          <br><br>
          <small class="text-muted"> (Admin only): </small>
          <%= link_to '<i class="fa fa-pencil-alt"></i>' .html_safe, edit_picture_path(@picture), class: "btn btn-sm btn-secondary" %>
          <%= link_to '<i class="fa fa-times"></i>' .html_safe, @picture, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
        <% end %>
        
        
      </div>
  </div>

</div>
</section>

app/views/welcome/_contact_us_section.html.erb
<section class="contact-section" id="contact">
  <div class="container">
    <h2>Contact Us Today! </h2>
    <hr>
    <p>
      Ready to start your next project with us? <br><br>Give us a call or send us an email and we will get back to you as soon as possible!
    </p>
    <br>
    <div class="row">
      <div class="col-lg-6 text-center">
        <i class="fas fa-phone fa-lg"></i>
        <p>847-420-2779</p>
      </div>
      <div class="col-lg-6 text-center">
        <i class="fas fa-envelope fa-lg"></i>
        <p><a href="mailto:k.zanoniinteriordesign@gmail.com">k.zanoniinteriordesign@gmail.com</a></p>
      </div>
    </div>
  </div>
</section>

app/views/welcome/index.html.erb
<div class="hero-image">
  <h1 class="hero-text">
      <mark>When the details matter...</mark><br>
      <small>
        <a href="#about" style="color: red">
          <i class="fas fa-lg fa-chevron-circle-down"></i>
        </a>
      </small>
  </h1>
</div>

<section class="about-section" id="about">
  <div class="container">
    <h2>Kathryn L. Zanoni Interior Design</h2>
    <hr class="light"><br>
    <p>
      Kate Zanoni founded Kathryn L. Zanoni Interior Design in 1999 with the understanding that details matter. With a natural ability Kate develops a design process around the needs and individual style of the client, while maintaining the principles of high end design.
    </p>
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-5">
        <br>
      
        <%= image_tag("kate-zanoni-interior-design.jpg", {class: "img-fluid", alt: "Kathryn Zanoni"}) %> 
      </div>
      <div class="col-xs-12 col-sm-6 col-md-7">
        <h3>A Consummate Designer</h3>
        <p>
            Kate has a background in the arts. She is a graduate of the Harrington Institute of Interior Design in Chicago and continues to gain valuable experience creating and developing living spaces for clients with the most sophisticated and far-ranging of tastes.
         </p>
        <h3>Interior Design as Process</h3>
        <p>
            The essence of interior design is the merging of form, function and finish with the aesthetic sensibilities of the client. From initial designs, through purchasing and construction management, to the installation of the finishing touches, Kathryn L Zanoni Interior Design will orchestrate the entire process to produce superior results.
        </p>
      </div> 
    </div>
    <br>
    <h3>A Sublime Result</h3>
    <p>
      The final product and the client’s satisfaction are the true measures of success. Kathryn L. Zanoni Interior Design is committed to crafting truly inspiring interior spaces and making the process enjoyable. For interior design that marries form, function and finish with the sublime details of one’s own style, <a href="#contact" style="color:#fff;" >contact us</a> today.
    </p>
    <p>
      <br>
      
        <a href="#services" style="color: red">
          <i class="fas fa-2x fa-chevron-circle-down"></i>
        </a>
      
      <!--<a href="#services" class="btn btn-danger btn-lg page-scroll">-->
      <!--  <i class="fa fa-angle-double-down"></i>&nbsp;Our Services-->
      <!--</a> -->
    </p>
  </div>
</section>

<section class="services-section" id="services">
  <div class="container">
    <h2>Our Services</h2>
    <hr class="primary">
 
                         
        <h3>Design</h3>
        <p class="text-muted">
          We understand that functionality is as valuable as form and can help you realize the maximum potential for your space.We will take your input, combine it with our expertise and design a fantastic space that suits your tastes and your needs. We’ll create a unique blend of your style and contemporary design philosophy. Don’t forget that half the fun is in the creation.
        </p>
      
                       
        <h3>Consultation</h3>
        <p class="text-muted">
          If you are not quite ready to embark on a full scale remodel and just want to explore your interior design options, we are delighted to help. Consultations can involve anything from simple advice on furnishings and fixtures to detailed plans on a fully remodeled or new space. We also can be available if you need assistance in managing your construction project. Our goal is to facilitate the interior design process for you by laying a good foundation and not allowing you to miss any of the important details.
        </p>
      
                           
        <h3>Purchasing</h3>
        <p class="text-muted">
         Shopping is an enjoyable pursuit when done at one’s leisure and on one’s own schedule. However, coordinating the purchase, delivery and installation of a large amount of furniture and fixtures can be a difficult process. It requires excellent organization and superb attention to detail. Kathryn L. Zanoni Interior Design will manage this challenging process for you.
        </p>
    
                             
        <h3>Finishing Touches</h3>
        <p class="text-muted">
          Sometimes, pulling all the loose ends together and completing a project is the most difficult task. We will assemble the final “punch list” to ensure that every last detail is accomplished, and that the project is finished to your complete satisfaction. The final result is a beautiful space that will be both comfortable for your everyday living, and one where you will feel proud to entertain your friends and families.
        </p>
     
    <p>
      <br>
        <!--<a href="#portfolio" class="hidden-xs btn btn-danger btn-lg page-scroll">-->
        <!--  <i class="fa fa-angle-double-down"></i>&nbsp;Our Portfolio-->
        <!--</a>-->
         <a href="#portfolio" style="color: red">
          <i class="fas fa-2x fa-chevron-circle-down"></i>
        </a>
    </p>             
  </div>
</section>

<section class="portfolio-section" id="portfolio">
  <h2>
    Our Portfolio
    <% if user_signed_in?  %>
      <small><%= link_to "+ Add new portfolio gallery", new_gallery_path, class: "btn btn-success" %> <small class="text-muted"> (Admin only) </small></small>
    <% end %>
  </h2>
  
  <div class="container">
    <div class="row">
      <!-- Dynamic galleries-->
      <% @galleries.each do |gallery| %>
        <div class="col-xs-12 col-lg-6" style="padding-top: 20px; margin-top: 40px; ">
          <%= link_to gallery_path(gallery) do %>
            <% if gallery.image.present? %>
            <!-- imag srcset later for smaller screen show medium ??? -->
              <%= image_tag gallery.image.url(:large), alt: gallery.try(:name), class: "img-fluid img-thumbnail" %>
            <% else %>
              <img src="https://via.placeholder.com/540x325" style=" height: 325px; max-width:100%">
            <% end %>
              <br>
              <%= gallery.name %>
              <% if user_signed_in? %>
                <br>
                <%= link_to '<i class="fa fa-pencil-alt"></i>' .html_safe, edit_gallery_path(gallery), class: "btn btn-sm btn-secondary" %>
                <%= link_to '<i class="fa fa-times"></i>' .html_safe, gallery, method: :delete, data: { confirm: 'Are you sure? This will delete any pictures in the gallery as well.' }, class: "btn btn-sm btn-danger" %> 
                <small class="text-muted">
                   (Admin only) <br>
                   <em>Display Order: </em><%= gallery.sort_order || "none" %> 
                </small>
              <% end %>
           
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <br>
   <p>
      <br>
        <a href="#contact" style="color: red">
          <i class="fas fa-2x fa-chevron-circle-down"></i>
        </a>
    </p>
</section>


<%= render 'welcome/contact_us_section' %>
  




  